### ISSUE TITLE
port to python

### ISSUE THREAD

**Issue by sillibird** [discoli/gohq#1]
why the heck would anyone use golang?

it's 2018

use a real language please.

**Comment by TheTetrabyte** [comment]
golang best lang

**Comment by discoli** [comment]
@sillibird https://benchmarksgame-team.pages.debian.net/benchmarksgame/faster/go-python3.html sorry hunny, couldn't hear you over the slowness of python.

Also couldn't hear you over Go actual compiling to a native binary
Oh wait, also couldn't hear you over Go actually being able to compile

**Comment by ItsPaulM** [comment]
Python in 2018

**Comment by discoli** [comment]
@ItsPaulM LUL

**Comment by TheTetrabyte** [comment]
LOL

**Comment by sillibird** [comment]
@discoli 

why flex speed and compilability when ur not using c++

**Comment by ItsPaulM** [comment]
because golang best lang

**Comment by discoli** [comment]
@sillibird because Go is the perfect balance between speed and convenience

and golang bestlang, don't argue it

**Comment by sillibird** [comment]
dont even know how to compile this garbage

should have used a real language where you could make use of this 

tfw you find exactly what you are looking for and it's in fking golang

**Comment by discoli** [comment]
To be honest, if you don't know Go then you shouldn't be trying to use a Go
library 🤷

**Comment by U-r-Unknown** [comment]
But bro do it scraps socket to get answers before

**Comment by U-r-Unknown** [comment]
During live? How many secs does it take

**Comment by discoli** [comment]
They get them as soon as the client does, they both use the same websocket

**Comment by U-r-Unknown** [comment]
Tnx bro

**Comment by discoli** [comment]
This is NOT a bot, this is a library, you can try make a bot out of it if you wanted to, lol
